FROM metabase/metabase:latest

ENV MB_DB_TYPE=postgres 
ENV MB_DB_HOST=<your-postgres-db-host> 
ENV MB_DB_PORT=5432 ENV 
MB_DB_DBNAME=<your-postgres-db-name> 
ENV MB_DB_USER=<your-postgres-db-username> 
ENV MB_DB_PASS=<your-postgres-db-password>

EXPOSE 3000
