services:

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    hostname: metabase
    volumes:
      - /dev/urandom:/dev/random:ro
      - db-data:/db/data
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabaseappdb
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: mysecretpassword
      MB_DB_HOST: postgres
    networks:
      - metanet1
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: metabase
      POSTGRES_DB: metabaseappdb
      POSTGRES_PASSWORD: mysecretpassword
    networks:
      - metanet1

  database_datavault:
    build: ./database
    volumes:
      - db-data:/db/data/
  
  etl:
    depends_on: 
      - database_datavault
    build: ./etl
    volumes:
      - db-data:/db/data/
      - etl-data:/filmmeisterapp/
    command: python3 film_meister_datavault_main.py

networks:
  metanet1:
    driver: bridge

volumes:
  db-data:
  etl-data: